In [50]:
import numpy as np
import pandas as pd

In [51]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [52]:
!wget $data

--2026-09-19 15:32:49--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.6’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.008s

2026-09-19 15:32:49 (77.1 MB/s) - ‘car_fuel_efficiency_2026.csv.6’ saved [635180/635180]

In [59]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [60]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [61]:
len(df)

10000

In [62]:
df['horsepower'].dtype

dtype('float64')

In [63]:
df['horsepower'].map(type).value_counts()

horsepower
<class 'float'>    10000
Name: count, dtype: int64

In [64]:
df['horsepower'].isna().sum()

np.int64(877)

In [57]:
# 1. Медиана до заполнения пропусков
median_before = df['horsepower'].median()

# 2. Самое частое значение
most_frequent = df['horsepower'].mode().iloc[0]

# 3. Заполняем пропуски этим значением
df['horsepower'] = df['horsepower'].fillna(most_frequent)

# 4. Снова вычисляем медиану
median_after = df['horsepower'].median()

print('Median before:', median_before)
print('Most frequent:', most_frequent)
print('Median after:', median_after)

Median before: 254.0
Most frequent: 252.0
Median after: 252.0

In [7]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = int(n - (n_val + n_test))

In [8]:
n, n_val, n_test, n_train

(10000, 2000, 2000, 6000)

Разбиваем датафрейм

In [9]:
df.iloc[:n_val]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
1995,1976,Europe,Gasoline,Rear-wheel drive,4,2390,6,NaN,4090,16.9,29.6
1996,1999,USA,Gasoline,All-wheel drive,4,2110,6,252.0,4270,19.4,28.0
1997,1983,Asia,Diesel,Rear-wheel drive,3,1960,6,226.0,4240,17.8,27.7
1998,2021,USA,Hybrid,Rear-wheel drive,4,2330,6,278.0,4480,17.5,32.9
1999,1981,Europe,Hybrid,Front-wheel drive,3,2400,7,279.0,4360,18.9,33.3

In [10]:
df_train = df.iloc[:n_train]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

получаем массив номеров строк

In [11]:
idx = np.arange(n)

In [12]:
idx

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

перемешиваем их в рандомном порядке

In [13]:
np.random.shuffle(idx)

In [14]:
idx

array([1839, 1881, 4747, ..., 3289, 3802, 2474], shape=(10000,))

присваиваем массиву и берем части для тренинга, валидации и теста

In [15]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

стабилизируем выборку, для того, чтобы она всегда была одинакова

In [16]:
np.random.seed(2)
np.random.shuffle(idx)

In [17]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

In [18]:
df_train

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
4541,2000,USA,Gasoline,Rear-wheel drive,4,2390,6,258.0,4290,19.5,30.3
3336,1992,USA,Diesel,Front-wheel drive,4,2280,6,270.0,4370,18.5,27.5
6085,2004,Europe,Diesel,Front-wheel drive,2,2130,6,247.0,3910,18.8,34.3
7496,2010,USA,Diesel,Front-wheel drive,4,2530,6,288.0,4520,19.5,30.8
6151,1985,Asia,Gasoline,Front-wheel drive,3,2140,6,230.0,4140,21.0,27.5
...,...,...,...,...,...,...,...,...,...,...,...
7177,1986,Asia,Gasoline,Front-wheel drive,2,2270,6,229.0,4010,18.7,34.7
523,2003,Europe,Gasoline,Rear-wheel drive,3,2180,5,219.0,4200,18.5,29.2
2725,1982,Europe,Hybrid,Rear-wheel drive,3,2450,6,261.0,4650,20.2,30.4
2811,2020,Asia,Gasoline,All-wheel drive,3,2470,6,262.0,4500,18.2,29.3
910,2012,USA,Diesel,Rear-wheel drive,3,2150,6,254.0,4180,17.8,34.1

In [19]:
len(df_train), len(df_val), len(df_test)

(6000, 2000, 2000)

переприсваиваем индексы

In [20]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

получаем значения для (вектора Y) (target variables)

In [21]:
y_train = np.log1p(df_train.vehicle_weight.values)
y_val = np.log1p(df_val.vehicle_weight.values)
y_test = np.log1p(df_test.vehicle_weight.values)

удаляем, чтобы случайно не затянуть данные

In [22]:
del df_train['vehicle_weight']
del df_val['vehicle_weight']
del df_test['vehicle_weight']

2.5 Linear regression

In [23]:
df_train.iloc[10]

model_year                          1977
origin                              Asia
fuel_type                         Diesel
drivetrain             Front-wheel drive
num_doors                              4
engine_displacement                 2170
num_cylinders                          6
horsepower                         259.0
acceleration                        19.0
fuel_efficiency_mpg                 29.2
Name: 10, dtype: object

In [24]:
xi = [261, 25.3, 19.2]

In [25]:
w0 = 0
w = [1, 1, 1]

In [26]:
def linear_regression(xi):
    n = len(xi)
    pred = w0

    for j in range(n):
        pred = pred + w[j] * xi[j]

    return pred

In [27]:
xi = [261, 25.3, 19.2]
w0 = 0
w = [1, 1, 1]

In [28]:
linear_regression(xi)

305.5

In [29]:
np.log(305.5)

np.float64(5.72194977861165)

In [30]:
np.expm1(305.5)

np.float64(4.7529606793260716e+132)

In [31]:
np.log1p(4.7529606793260716e+132)

np.float64(305.5)

In [32]:
df ['fuel_type'].nunique()

3

In [33]:
df.columns[df.isna().any()]

Index(['horsepower', 'acceleration'], dtype='str')

In [34]:
df.isna().any().sum()

np.int64(2)

In [35]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [36]:
df_train.loc[
    df_train['origin'] == 'Asia',
    'fuel_efficiency_mpg'
].max()

np.float64(41.2)

In [37]:
asia = df_train[df_train['origin'] == 'Asia']
asia.loc[asia['fuel_efficiency_mpg'].idxmax()]

model_year                          2022
origin                              Asia
fuel_type                         Diesel
drivetrain             Front-wheel drive
num_doors                              4
engine_displacement                 1990
num_cylinders                          6
horsepower                         225.0
acceleration                        17.2
fuel_efficiency_mpg                 41.2
Name: 3312, dtype: object

In [47]:
df['horsepower'].dtype

dtype('O')

In [46]:
median_before = df['horsepower'].median()

most_frequent = df['horsepower'].mode().iloc[0]

df['horsepower'] = df['horsepower'].fillna(most_frequent)

median_after = df['horsepower'].median()

print('Median before:', median_before)
print('Most frequent:', most_frequent)
print('Median after:', median_after)

TypeError: Cannot convert [243.0 272.0 267.0 ... 267.0 270.0 295.0] to numeric

In [40]:
median_before = df['horsepower'].median()

In [41]:
median_before

np.float64(254.0)

In [42]:
most_frequent = df['horsepower'].mode().iloc()

In [43]:
most_frequent

In [44]:
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [45]:
median_after = df['horsepower'].median()

TypeError: Cannot convert [243.0 272.0 267.0 ... 267.0 270.0 295.0] to numeric