In [3]:
import numpy as np
import pandas as pd

In [4]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [5]:
!wget $data

--2026-09-24 17:01:46--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.8’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.009s

2026-09-24 17:01:46 (70.2 MB/s) - ‘car_fuel_efficiency_2026.csv.8’ saved [635180/635180]

In [6]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [7]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [8]:
len(df)

10000

In [9]:
df['horsepower'].dtype

dtype('float64')

In [10]:
df['horsepower'].map(type).value_counts()

horsepower
<class 'float'>    10000
Name: count, dtype: int64

In [11]:
df['horsepower'].isna().sum()

np.int64(877)

In [12]:
# 1. Медиана до заполнения пропусков
median_before = df['horsepower'].median()

# 2. Самое частое значение
most_frequent = df['horsepower'].mode().iloc[0]

# 3. Заполняем пропуски этим значением
df['horsepower'] = df['horsepower'].fillna(most_frequent)

# 4. Снова вычисляем медиану
median_after = df['horsepower'].median()

print('Median before:', median_before)
print('Most frequent:', most_frequent)
print('Median after:', median_after)

Median before: 254.0
Most frequent: 252.0
Median after: 252.0

In [13]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = int(n - (n_val + n_test))

In [14]:
n, n_val, n_test, n_train

(10000, 2000, 2000, 6000)

Разбиваем датафрейм

In [15]:
df.iloc[:n_val]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
1995,1976,Europe,Gasoline,Rear-wheel drive,4,2390,6,252.0,4090,16.9,29.6
1996,1999,USA,Gasoline,All-wheel drive,4,2110,6,252.0,4270,19.4,28.0
1997,1983,Asia,Diesel,Rear-wheel drive,3,1960,6,226.0,4240,17.8,27.7
1998,2021,USA,Hybrid,Rear-wheel drive,4,2330,6,278.0,4480,17.5,32.9
1999,1981,Europe,Hybrid,Front-wheel drive,3,2400,7,279.0,4360,18.9,33.3

In [16]:
df_train = df.iloc[:n_train]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

получаем массив номеров строк

In [17]:
idx = np.arange(n)

In [18]:
idx

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

перемешиваем их в рандомном порядке

In [19]:
np.random.shuffle(idx)

In [20]:
idx

array([7821, 8736, 7237, ..., 9255, 9471, 8586], shape=(10000,))

присваиваем массиву и берем части для тренинга, валидации и теста

In [21]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

стабилизируем выборку, для того, чтобы она всегда была одинакова

In [22]:
np.random.seed(2)
np.random.shuffle(idx)

In [23]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

In [24]:
df_train

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
1553,1991,USA,Hybrid,Front-wheel drive,3,2340,7,253.0,4420,18.5,30.0
593,1984,Asia,Gasoline,All-wheel drive,4,2520,7,252.0,4730,19.2,27.2
2136,1991,Asia,Hybrid,Front-wheel drive,3,2500,7,279.0,4110,18.5,33.1
3666,2009,USA,Gasoline,Front-wheel drive,3,2220,6,245.0,4050,18.1,29.4
9142,2016,Europe,Gasoline,Front-wheel drive,3,2300,6,253.0,4140,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
8601,1987,Europe,Gasoline,Front-wheel drive,3,2220,6,241.0,4040,20.3,28.1
455,1982,Europe,Diesel,Front-wheel drive,4,2550,6,263.0,4640,NaN,26.7
4503,2003,USA,Gasoline,Front-wheel drive,2,2390,6,255.0,4270,16.1,26.1
985,2024,Asia,Gasoline,Front-wheel drive,3,2500,7,261.0,4550,17.3,31.9
5107,1976,USA,Gasoline,Rear-wheel drive,3,2090,6,252.0,4280,16.9,28.1

In [25]:
len(df_train), len(df_val), len(df_test)

(6000, 2000, 2000)

переприсваиваем индексы

In [26]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

получаем значения для (вектора Y) (target variables)

In [27]:
y_train = np.log1p(df_train.vehicle_weight.values)
y_val = np.log1p(df_val.vehicle_weight.values)
y_test = np.log1p(df_test.vehicle_weight.values)

удаляем, чтобы случайно не затянуть данные

In [28]:
del df_train['vehicle_weight']
del df_val['vehicle_weight']
del df_test['vehicle_weight']

2.5 Linear regression

In [29]:
df_train.iloc[10]

model_year                          2023
origin                               USA
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                              3
engine_displacement                 2250
num_cylinders                          6
horsepower                         251.0
acceleration                        19.1
fuel_efficiency_mpg                 31.1
Name: 10, dtype: object

In [30]:
xi = [261, 25.3, 19.2]

In [31]:
w0 = 0
w = [1, 1, 1]

In [32]:
def dot(xi, w):
    n = len(xi)

    res = 0.0

    for j in range(n):
        res = res + xi(j) + w(j)

    return res

In [33]:
def linear_regression(xi):
      return w0 + dot(xi, w)

In [34]:
w_new = [w0] + w

In [35]:
xi_new = [1] + xi

In [36]:
def linear_regression(xi):
      return w0 + dot(xi_new, w_new)

In [39]:
X

NameError: name 'X' is not defined

In [37]:
linear_regression(xi)

TypeError: 'list' object is not callable

In [38]:
xi = [261, 25.3, 19.2]
w0 = 0
w = [1, 1, 1]

In [28]:
linear_regression(xi)

305.5

In [29]:
np.log(305.5)

np.float64(5.72194977861165)

In [30]:
np.expm1(305.5)

np.float64(4.7529606793260716e+132)

In [31]:
np.log1p(4.7529606793260716e+132)

np.float64(305.5)

2.6 - Linear Regression: Vector Form